### ISSUE TITLE
elif instead of if?

### ISSUE THREAD

**Issue by somedadaism** [iamjawa/zork-py#4]
I just used the program (with python2). In the 10th loop one has to use elif instead of if - otherwise the program will not run as intended?! 
Am I missing something?

**Comment by iamjawa** [comment]
Which line is it that needs replacing with elif in the source?

**Comment by somedadaism** [comment]
Any if between lines 147 to 167.
Otherwise the final else will only refer to the previous if - so if I don't commit suicide I would be trapped in loop 10.
I think it would be good stile make similar changes in the other loops too, though they work the because the last if statement would change the loop.

**Comment by Ksisky** [comment]
# Code for reference:
```python
if cave_inp.lower() == ("take skeleton"):
	print("---------------------------------------------------------")
	print("Why would you do that? Are you some sort of sicko?")
	loop = 10
if cave_inp.lower() == ("smash skeleton"):
	print("---------------------------------------------------------")
	print("Sick person. Have some respect mate.")
	loop = 10
if cave_inp.lower() == ("light up room"):
	print("---------------------------------------------------------")
	print("You would need a torch or lamp to do that.")
	loop = 10
if cave_inp.lower() == ("break skeleton"):
	print("---------------------------------------------------------")
	print("I have two questions: Why and With What?")
	loop = 10
if cave_inp.lower() == ("go down staircase"):
	loop = 11
if cave_inp.lower() == ("scale staircase"):
	loop = 11
```

@somedadaism When the else statement is executed nothing is changed, and because loop == 10, the while statement repeats the process over, giving the user another chance. If anything, this would have to do with the code inside the if statements, not whether they are if or elif.

@iamjawa I do not see this as an issue, and I believe it can be closed.

**Comment by belle318** [comment]
I was getting the same thing as @somedadaism . I would be stuck on Loop 10 over and over until committing suicide to get out of the loop.

I believe @somedadaism  was saying the suicide loop should be a "elif" statement instead of an "if" 
Reference code:
Line 167        `elif cave_inp.lower() == ("suicide"):`

**Comment by abdelmalek13** [comment]
I have the same issue 
'elif' instead of 'if'

**Comment by somedadaism** [comment]
```
                # some other if conditions which may cause loop != 10.
                # say for an example loop == 11.
		if cave_inp.lower() == ("suicide"):
			print("---------------------------------------------------------")
			print("You throw yourself down the staircase as an attempt at suicide. You die.")
			print("---------------------------------------------------------")
			suicide_inp = raw_input("Do you want to continue? Y/N ")
			if suicide_inp.lower() == ("n"):
				import os
				quit(1)
			if suicide_inp.lower() == ("y"):
				loop = 3
                # if I avoid suicide then inevetably this else condition will be execuded,
                # because it referes to the above if statement.
		else:
			print("---------------------------------------------------------")
			loop = 10
               # here loop == 10 holds and we are trapped forever...
```
